// Data Smith — realistic seed-data generator, ported from Time-Traveler's
// data_smith.yml agent (MIT License, Copyright (c) 2026-present GitLab Inc.,
// see ACKNOWLEDGMENTS.md). Their agent infers realistic values purely from
// column names; this port implements the same inference rules deterministically
// in Node so it works without an LLM.

const FIRST = ["Alice", "Ben", "Carla", "David", "Elena", "Farid", "Grace", "Hugo", "Iris", "Jamal"];
const LAST = ["Thornton", "Nguyen", "Okafor", "Silva", "Kaur", "Meyer", "Rossi", "Haddad", "Cohen", "Park"];

// Deterministic pseudo-random so the same schema always seeds the same rows
function pick(arr, i) {
  return arr[i % arr.length];
}

// One realistic value for a column, inferred from its name + type (Data Smith's rules)
function valueFor(col, type, rowIndex) {
  const n = col.toLowerCase();
  const t = (type || "").toLowerCase();
  const first = pick(FIRST, rowIndex);
  const last = pick(LAST, rowIndex);

  if (n === "email" || n.endsWith("_email"))
    return `'${first.toLowerCase()}.${last.toLowerCase()}${rowIndex}@example.com'`;
  if (n === "first_name") return `'${first}'`;
  if (n === "last_name") return `'${last}'`;
  if (n === "username") return `'${first.toLowerCase()}${rowIndex}'`;
  if (n === "name" || n.endsWith("_name")) return `'${first} ${last}'`;
  if (n === "phone" || n === "phone_number" || n === "mobile")
    return `'+1-555-0${String(100 + rowIndex).slice(-3)}-${String(1000 + rowIndex).slice(-4)}'`;
  if (n === "created_at" || n === "updated_at" || n.includes("timestamp") || t.includes("timestamp"))
    return `'2026-0${(rowIndex % 9) + 1}-15 10:00:00'`;
  if (["price", "amount", "cost", "total"].includes(n)) return String((rowIndex + 1) * 19.99);
  if (n === "status") return pick(["'active'", "'inactive'", "'pending'"], rowIndex);
  if (["description", "bio", "notes", "content", "body"].includes(n))
    return `'Sample ${n} text for row ${rowIndex + 1}.'`;
  if (t.includes("bool")) return rowIndex % 2 === 0 ? "true" : "false";
  if (t.includes("uuid")) return "gen_random_uuid()";
  if (t.includes("int") || t.includes("serial") || t.includes("numeric") || t.includes("decimal"))
    return String(rowIndex + 1);
  if (t.includes("date")) return `'2026-0${(rowIndex % 9) + 1}-15'`;
  return `'value_${rowIndex + 1}'`;
}

// Parse a CREATE TABLE block into { table, columns: [{name, type, nullable, unique}] }
function parseCreateTable(sql) {
  const m = sql.match(/CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?["'`]?(\w+)["'`]?\s*\(([\s\S]*?)\)\s*;/i);
  if (!m) return null;
  const table = m[1];
  const body = m[2];
  const columns = [];
  for (let line of body.split(",")) {
    line = line.trim();
    if (!line) continue;
    // skip table-level constraints
    if (/^(PRIMARY|FOREIGN|UNIQUE|CONSTRAINT|CHECK)\b/i.test(line)) continue;
    const cm = line.match(/^["'`]?(\w+)["'`]?\s+([A-Za-z0-9()]+)/);
    if (!cm) continue;
    columns.push({
      name: cm[1],
      type: cm[2],
      nullable: !/NOT\s+NULL/i.test(line),
      unique: /UNIQUE/i.test(line),
      isPk: /PRIMARY\s+KEY/i.test(line),
    });
  }
  return columns.length ? { table, columns } : null;
}

// Generate seed SQL for all CREATE TABLE statements found in `schemaSql`
function generateSeed(schemaSql, rowsPerTable = 6) {
  const tables = [];
  const createRe = /CREATE\s+TABLE[\s\S]*?\)\s*;/gi;
  let match;
  while ((match = createRe.exec(schemaSql))) {
    const parsed = parseCreateTable(match[0]);
    if (parsed) tables.push(parsed);
  }
  if (!tables.length) return { sql: "", tables: [] };

  const blocks = [
    "-- ============================================================",
    "-- Seed data generated by Data Smith",
    `-- Tables: ${tables.map((t) => t.table).join(", ")}`,
    "-- ============================================================",
    "",
  ];

  for (const { table, columns } of tables) {
    const cols = columns.map((c) => c.name);
    // leave one nullable column NULL (Data Smith's "verify nullable handling")
    const nullableCol = columns.find((c) => c.nullable && !c.unique && !c.isPk)?.name;
    const rows = [];
    for (let i = 0; i < rowsPerTable; i++) {
      const vals = columns.map((c) =>
        c.name === nullableCol && i < 2 ? "NULL" : valueFor(c.name, c.type, i)
      );
      rows.push(`  (${vals.join(", ")})`);
    }
    const uniqueCol = columns.find((c) => c.unique)?.name;
    const onConflict = uniqueCol ? `ON CONFLICT (${uniqueCol}) DO NOTHING;` : "ON CONFLICT DO NOTHING;";
    blocks.push(
      `-- Table: ${table} (${rowsPerTable} rows)`,
      `INSERT INTO ${table} (${cols.join(", ")}) VALUES`,
      rows.join(",\n"),
      onConflict,
      ""
    );
  }
  return { sql: blocks.join("\n"), tables: tables.map((t) => t.table) };
}

// AI-powered generation — this is how Time-Traveler's Data Smith actually works
// (a Claude-powered agent). Sends the real schema to the LLM and gets back seed
// SQL tailored to it. Falls back to the deterministic parser above if no AI key.
const DATA_SMITH_PROMPT = (schemaSql, rows) =>
  "You are Data Smith, a seed-data generator (Time-Traveler agent). Read this SQL " +
  "schema and generate realistic INSERT statements.\n" +
  "Rules: generate " + rows + " rows per table; FK-safe insertion order (no-FK tables first); " +
  "infer realistic values purely from column names and types (email→real emails, name→real names, " +
  "phone→phone format, created_at→past timestamps, price/amount→numbers, status→CHECK values); " +
  "leave 1-2 nullable columns NULL per table; honor UNIQUE and CHECK constraints; " +
  "end each table's block with ON CONFLICT DO NOTHING;. Output RAW SQL ONLY, no prose.\n\n" +
  "Schema:\n" + schemaSql;

const SEED_SCHEMA = {
  type: "object",
  properties: { sql: { type: "string" }, tables: { type: "array", items: { type: "string" } } },
  required: ["sql", "tables"],
  additionalProperties: false,
};

async function generateSeedAI(schemaSql, rowsPerTable = 6) {
  const prompt = DATA_SMITH_PROMPT(schemaSql, rowsPerTable);

  if (process.env.ANTHROPIC_API_KEY) {
    const Anthropic = require("@anthropic-ai/sdk");
    const client = new Anthropic();
    const response = await client.messages.create({
      model: "claude-opus-4-8",
      max_tokens: 16000,
      thinking: { type: "adaptive" },
      output_config: { format: { type: "json_schema", schema: SEED_SCHEMA } },
      messages: [{ role: "user", content: prompt }],
    });
    const textBlock = response.content.find((b) => b.type === "text");
    return { ...JSON.parse(textBlock.text), provider: "claude" };
  }

  if (process.env.OPENROUTER_API_KEY) {
    const MODELS = [
      "cohere/north-mini-code:free",
      "google/gemma-4-31b-it:free",
      "inclusionai/ling-3.0-flash:free",
    ];
    for (const model of MODELS) {
      try {
        const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
          method: "POST",
          headers: {
            Authorization: `Bearer ${process.env.OPENROUTER_API_KEY}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            model,
            messages: [{ role: "user", content: prompt + '\n\nReturn ONLY JSON: {"sql": string, "tables": string[]}.' }],
          }),
        });
        if (!res.ok) throw new Error(`OpenRouter ${res.status}`);
        const data = await res.json();
        let text = (data.choices?.[0]?.message?.content || "").replace(/```json|```/g, "").trim();
        const a = text.indexOf("{"), b = text.lastIndexOf("}");
        if (a === -1 || b === -1) throw new Error("no JSON");
        return { ...JSON.parse(text.slice(a, b + 1)), provider: `openrouter/${model.split(":")[0]}` };
      } catch (err) {
        console.error(`Data Smith ${model} failed:`, err.message);
      }
    }
  }

  // deterministic fallback (no AI key configured)
  return { ...generateSeed(schemaSql, rowsPerTable), provider: "deterministic" };
}

module.exports = { generateSeed, generateSeedAI, parseCreateTable };
